"""empty message

Revision ID: 2561ab0178ea
Revises: 82e322010fe1
Create Date: 2021-02-22 13:20:18.434417

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2561ab0178ea"
down_revision = "82e322010fe1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "member_invites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("organization_id", sa.Integer(), nullable=True),
        sa.Column("token", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "email",
            "organization_id",
            name="member_invites_email_organization_id_uniq_const",
        ),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("member_invites")
    # ### end Alembic commands ###
